/*

SCHEMA É UMA MANEIRA DE ORGANIZAR AS TABELAS, NÃO É APENAS ISSO, MAS AUXILIA A ESTRUTURAÇÃO.


*/
    USE AdventureWorks2019 --PARA DEFINIR ONDE SERÁ EXECUTADA A QUERY ABAIXO
    GO -- O "GO" ENCERRA O "USE
    SELECT * FROM INFORMATION_SCHEMA.TABLES 

    

    SELECT * FROM INFORMATION_SCHEMA.TABLES --CONHECER A ESTRUTURA DO BANCO DE DADOS TABELAS, VIEWS, ETC;

    SELECT TOP 100 * FROM INFORMATION_SCHEMA.COLUMNS -- USAR SEMPRE "TOP" PARA CONHECER O BANCO PARA NÃO SOBRECARREGA-LO 

    SELECT TOP 100 * FROM INFORMATION_SCHEMA.COLUMNS

    SELECT * FROM INFORMATION_SCHEMA.COLUMNS -- INFORMATION_SCHEMA é padrão, pode ser usado em outros SGBD's
     WHERE TABLE_SCHEMA = 'Person'
       AND TABLE_NAME = 'Person'
    
    
    -- ESQUEMA PADRÃO DO DBO
    --SELECT * FROM [Nome_da_base].[Nome_do_Schema].[Nome_da_tabela]

   

